# -*- coding: utf-8 -*-
"""IMDB moving rating .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WBnywXbYc3_GtRpm-o7QUqmXzLRO5c6s
"""

#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

#load data set
data = pd.read_csv("IMDb Movies India.csv", encoding='latin1')

data.head()

data.info()

data.describe()

#Check Missing Values
data.isnull().sum()

#Remove Rows without Rating
data = data.dropna(subset=['Rating'])

# Convert Year column to string first
data['Year'] = data['Year'].astype(str)

# Extract 4-digit year
data['Year'] = data['Year'].str.extract(r'(\d{4})', expand=False)

# Convert to numeric
data['Year'] = pd.to_numeric(data['Year'], errors='coerce')

print(data['Year'].head(10))

data['Duration'] = data['Duration'].str.replace(' min','',regex=False)
data['Duration'] = pd.to_numeric(data['Duration'])

data['Votes'] = data['Votes'].astype(str).str.replace(',', '')
data['Votes'] = pd.to_numeric(data['Votes'], errors='coerce')

data = data.dropna(subset=['Rating'])

data.head()

X = data.drop('Rating', axis=1)

y = data['Rating']

categorical_features = [
    'Name',
    'Genre',
    'Director',
    'Actor 1',
    'Actor 2',
    'Actor 3'
]

numerical_features = [
    'Year',
    'Duration',
    'Votes'
]

numeric_transformer = SimpleImputer(strategy='median')

categorical_transformer = Pipeline(
[
('imputer', SimpleImputer(strategy='most_frequent')),
('encoder', OneHotEncoder(handle_unknown='ignore'))
]
)

preprocessor = ColumnTransformer(
[
('num', numeric_transformer, numerical_features),
('cat', categorical_transformer, categorical_features)
]
)

X_train, X_test, y_train, y_test = train_test_split(
X,
y,
test_size=0.2,
random_state=42
)

model = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(
        n_estimators=5,
        max_depth=8,
        random_state=42,
        n_jobs=-1
    ))
])

model.fit(X_train, y_train)

predictions = model.predict(X_test)

mae = mean_absolute_error(y_test, predictions)
print("MAE:", mae)

rmse = np.sqrt(mean_squared_error(y_test, predictions))
print("RMSE:", rmse)

comparison = pd.DataFrame({
'Actual Rating': y_test,
'Predicted Rating': predictions
})

comparison.head(20)

plt.figure(figsize=(8,6))
plt.scatter(y_test, predictions)
plt.plot([y_test.min(), y_test.max()],
         [y_test.min(), y_test.max()],
         'r--')
plt.xlabel("Actual Rating")
plt.ylabel("Predicted Rating")
plt.title("Actual vs Predicted Ratings")
plt.show()

actors = data['Actor 1'].value_counts().head(10)

plt.figure(figsize=(10,6))
plt.barh(actors.index, actors.values)
plt.title("Top 10 Lead Actors")
plt.xlabel("Number of Movies")
plt.ylabel("Actor")
plt.show()